name: "medical_project"
version: "1.0.0"
config-version: 2

profile: "medical_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  medical_project:
    staging:
      materialized: view
    marts:
      materialized: table
