version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: telegram_data_db
      POSTGRES_USER: telegram_user
      POSTGRES_PASSWORD: fualaa@6717
    ports:
      - "5432:5432"

  app:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env 
    depends_on:
      - db
    command: bash -c "uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
